### PR TITLE
Update social auth to 2.0 and django-mptt to 0.9.1

### LINKED ISSUE #1151: Update social auth to 2.0
Python social auth 2.0 has been released a while ago including fixes to bugs that forced to me to use `misago-social-auth` fork in Misago.

### PR DESCRIPTION
**Pull request by ali-alsabbah**
misago-social-auth-app-django replaced with social-auth-app-django
requirements.in updated and new requirements.txt generated

Fixes #1151 #1172

### CODE REVIEW

**Comment by rafalp** [comment]
I am surprised. It looks like bunch of dependencies have been removed, and yet build is passing. I'm wondering if this is something messed up on my local pip setup?

**Comment by ali-alsabbah** [comment]
No clue. If it matters, I used Pipenv to create the virtual environment and install pip-tools on my end, but I used pip-tools to generate the requirements.txt like you asked.

**Comment by ali-alsabbah** [comment]
I redid it without Pipenv and it produced the same requirements.txt as this

**Comment by rafalp** [comment]
Mind sharing what OS and system python are you on?

On sidenote, I see that deps were updated, but social auth core is still `1.x`. Do you know if there's no django social auth app for `2.x`?

**Comment by ali-alsabbah** [comment]
MacOS 10.14.1
Python 3.7.1

I do not know the answer to the second question.

**Comment by rafalp** [comment]
I'll merge those tomorrow when I see whats going on with my pip-tools ;)

**Comment by rafalp** [comment]
I've tried this locally and looks like `pip-compile` is influenced and messed up by existing pip caches. I've cleared all my caches and got result like you except with `social-auth-core==2.0.0`.

Can you please clear your `~/Library/Caches/pip`, delete `requirements.txt`, delete your venv, and create new venv and then regenerate `requirements.txt` using `pip-compile --output-file requirements.txt requirements.in` again?

**Comment by rafalp** [comment]
@ali-alsabbah could you also take care of #1172 (updating mptt to 0.9.1)?

**Comment by ali-alsabbah** [comment]
Done

**Pull request merged**
