### PR TITLE
Update SetupMaintenance.md

### PR DESCRIPTION
**Pull request by GMTechBen**
Changed "taks" to "tasks"

### CODE REVIEW

**Comment by rafalp** [comment]
Hey, thanks for opening pull request.

I see you've started with PR'ing typo correction. Is this a part of larger effort on your side to proofread Misago's docs?

**Comment by GMTechBen** [comment]
Hey, no problem.

I'm actually just reading through the documentation before setting up Misago. Found the project yesterday and really like it. So far I noticed a couple typos, but am just getting started. Maybe I should hold off on merging the PR in case I find more?

Wasn't sure if you'd prefer lots of small PRs or one larger PR.

**Comment by rafalp** [comment]
> Maybe I should hold off on merging the PR in case I find more?

That would be great.

**Comment by GMTechBen** [comment]
*fyi: Opening separate PR

**Pull request closed without merging**
