### PR TITLE
Update Django to 2.1, Rest Framework to 3.8, add Python 3.7 support

### PR DESCRIPTION
**Pull request by WojtekReu**

### CODE REVIEW

**Comment by rafalp** [comment]
Nice, thanks!

I see this PR adds py 3.7 support,  bumps our Django to 2.1 and updates Rest Framework as well? Thats okay. I've been worried to move off the MVP (in past I've tried keeping up with Django releases and the churn was killing me), but I see that 2.1 support overlaps with future Django 2.2 LTS release, so its okay.

I have few questions though:

- The password in tests has changed to `ogasiM200_`. What forced this change? I don't remember the exact version, but for some time now Misago's `create_user` no longer requires the password argument at all, so we could drop it alltogether in tests that need user account, but don't use the authentication flow.
- Form template has been updated to include asterisk for required fields. That change feels out of scope, and asterisks on required fields are something I'm disagreeing with personaly - we are communicating that fields are optional via help-text which I find superior way to asterisks.
- I see that API response assertions have changed. Is this result of Rest Framework update? This is breaking change as frontend is no longer able to extract messages that need to be displayed to the user.
- I see that `__future__`, `six` and `u""`  are still present, we don't need those if we are killing py2k support.
- Is there any reason we want to support py3.5? I know it has some syntax differences to py3.6 (eg. type annotations), but there are some conveniences in Py36 like functions being smart enough to encode/decode things between str/bytes automatically that I would like to use.
- We should also update travis config to mark unsupported python versions as allowed to fail.

Still, thank you for helping out, this is great step to making Misago more awesome, and Django 2 support is much requested feature 👍

**Comment by WojtekReu** [comment]
> I see this PR adds py 3.7 support, bumps our Django to 2.1 and updates Rest Framework as well? Thats okay. I've been worried to move off the MVP (in past I've tried keeping up with Django releases and the churn was killing me), but I see that 2.1 support overlaps with future Django 2.2 LTS release, so its okay.

I'm trying to update all packages from requirements. 


> I have few questions though:
> 
>     * The password in tests has changed to `ogasiM200_`. What forced this change? I don't remember the exact version, but for some time now Misago's `create_user` no longer requires the password argument at all, so we could drop it alltogether in tests that need user account, but don't use the authentication flow.

Django forced this change. Old password caused validation error "Password is too simply" or something like that.


>     * Form template has been updated to include asterisk for required fields. That change feels out of scope, and asterisks on required fields are something I'm disagreeing with personaly - we are communicating that fields are optional via help-text which I find superior way to asterisks.

OK, I'll try disable asterisk for required fields.


>     * I see that API response assertions have changed. Is this result of Rest Framework update? This is breaking change as frontend is no longer able to extract messages that need to be displayed to the user.

It caused errors. Probably it still has to be checked. I didn't notice any missing errors.


>     * I see that `__future__`, `six` and `u""`  are still present, we don't need those if we are killing py2k support.

I tried to do as small changes as needed. I agree to remove all outdated features.


>     * Is there any reason we want to support py3.5? I know it has some syntax differences to py3.6 (eg. type annotations), but there are some conveniences in Py36 like functions being smart enough to encode/decode things between str/bytes automatically that I would like to use.

Yes, there is no reason to support py3.5 I think.


>     * We should also update travis config to mark unsupported python versions as allowed to fail.

I changed travis configuration. Do you mean to remove support for python 2.7, 3.4, 3.5?


> Still, thank you for helping out, this is great step to making Misago more awesome, and Django 2 support is much requested feature +1

I continue update in my available time. Thanks.

**Comment by rafalp** [comment]
> Django forced this change. Old password caused validation error "Password is too simply" or something like that.

I think we should axe some password validators from test project, so we still touch that mechanic, but don't fight against it.

> It caused errors. Probably it still has to be checked. I didn't notice any missing errors.

We don't have any front-to-back integration tests, so I guess I'll have to go trough all the frontend code and see where I'm handling errors. Damm, but its good reason for me to finally do some cleanups in our UI code.

> Yes, there is no reason to support py3.5 I think.

Lets axe it then, and stick to 3.6 and 3.7

> I changed travis configuration. Do you mean to remove support for python 2.7, 3.4, 3.5?

You can mark tests as allowed to fail: https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail

**Comment by rafalp** [comment]
I've just moved Misago's codebase to Python 3.6-only with #1122

That should get us little closer to 3.7/Django2.1 support.

**Comment by rafalp** [comment]
Another update: I've removed `crispy_forms` from dependencies with #1128 and #1129.

I am now working on making rest API tests also test response JSON shape, after that we should be be ready for another go with moving Misago to Py 3.7 with Django 2.1. 👍

**Comment by rafalp** [comment]
Superseded by #1228

**Pull request closed without merging**
