### PR TITLE
setup.py for Misago 0.5.x

### PR DESCRIPTION
**Pull request by sirex**
One of the strengths of Python is that you can install python packages in many
ways and use them in you project.

Unfortunately that is not the case with Misago. In stead of using standard
python tools and infrastructure one has to do exception for Misago and  do the
deployment in a different way.

This change fixes that by making Misago fully working Python package.

The package also includes data files. Data files can be accessed using
setuptools:

    import pkg_resources as pres

    MISAGO_DIR = pres.resource_filename('misago', '')

    STATICFILES_DIRS = (
        os.path.join(MISAGO_DIR, 'attachments')
        os.path.join(MISAGO_DIR, 'media')
        os.path.join(MISAGO_DIR, 'static')
    )

### CODE REVIEW

**Comment by sirex** [comment]
@rafalp ping.

**Comment by rafalp** [comment]
Hello,

I am well aware of this PR hanging around, however if I’ve merged it in and published 0.5 on PIP, that would be message to folk out there that Miasago 0.5 is well worth shot at prod sites and thus influx of bugs for 0.5 that I’ll wont have time to handle with as I am already having very restricted time I can put into 0.6.

You said you want to uplift 0.5 to Django 1.8. If you don’t mind taking few extra tasks that I’ve mentioned on forums (
http://misago-project.org/thread/how-stable-misago-is-445/#post-1366) as well as future bug reports then I can merge this PR in.

~ralph

**Comment by sirex** [comment]
It is possible tell folks, that 0.5 is a [pre-release](https://www.python.org/dev/peps/pep-0440/#pre-releases), this would require `--pre` flag (`pip install --pre misago`) explicitly telling, that you want to install a pre-release. Just `pip install misago` would not work.

To make `--pre` flag work `0.5` version should be changed to `0.5a1`.

Why I need this? Well I'm planning to run a forum based on Misago and would like to do a proper deployment using standard Python packaging tools.

Yes, I would like to uplift 0.5 to Django 1.8 and I don't mind to take few extra tasks, but I am more interested in running and maintaining single forum instance, not the whole Misago project. And I don't mind taking few extra tasks if they are directly related with the forum I run.

The forum I'm talking about is my hobby project and I can spend only few hours per week with some random weekends when I can sit whole day or two to take a bigger task.

**Comment by rafalp** [comment]
Fair enough :]

Update PR for pre release and I’ll merge and publish it on pip.

**Comment by rafalp** [comment]
I am greatly disappointed that github didn't notify me about updates to this PR.

**Pull request merged**
